In [33]:
#libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [34]:
#loading dataset
df = pd.read_csv('data.csv')
df.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [35]:
df['thumbnail'][0]

'http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'

In [36]:
df.shape

(6810, 12)

In [37]:
df.isnull().sum()

isbn13               0
isbn10               0
title                0
subtitle          4429
authors             72
categories          99
thumbnail          329
description        262
published_year       6
average_rating      43
num_pages           43
ratings_count       43
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.columns

Index(['isbn13', 'isbn10', 'title', 'subtitle', 'authors', 'categories',
       'thumbnail', 'description', 'published_year', 'average_rating',
       'num_pages', 'ratings_count'],
      dtype='object')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6711 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB

#Feature Selection

In [41]:
#feature selection
df = df[['title', 'authors', 'categories','description', 'average_rating','ratings_count','thumbnail', 'isbn13']]
df.head()

,title,authors,categories,description,average_rating,ratings_count,thumbnail,isbn13
0,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...,3.85,361.0,http://books.google.com/books/content?id=KQZCP...,9780002005883
1,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,3.83,5164.0,http://books.google.com/books/content?id=gA5GP...,9780002261982
2,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,3.97,172.0,http://books.google.com/books/content?id=OmQaw...,9780006163831
3,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,29532.0,http://books.google.com/books/content?id=FKo2T...,9780006178736
4,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,4.15,33684.0,http://books.google.com/books/content?id=XhQ5X...,9780006280897

In [42]:
df.shape

(6810, 8)

In [43]:
df.isnull().sum()

title               0
authors            72
categories         99
description       262
average_rating     43
ratings_count      43
thumbnail         329
isbn13              0
dtype: int64

#data cleaning

In [44]:
#removing null values
# df = df.dropna(subset=['categories','description','thumbnail'])

In [45]:
#filling null values
df['authors'] = df['authors'].fillna(' ')
df['average_rating'] = df['average_rating'].fillna(df['average_rating'].mean())
df['ratings_count'] = df['ratings_count'].fillna(0)
df['categories'] = df['categories'].fillna('')
df['description'] = df['description'].fillna('')
df['thumbnail'] = df['thumbnail'].fillna('https://upload.wikimedia.org/wikipedia/en/6/60/No_Picture.jpg')

In [46]:
df.isnull().sum()

title             0
authors           0
categories        0
description       0
average_rating    0
ratings_count     0
thumbnail         0
isbn13            0
dtype: int64

In [47]:
df = df.reset_index(drop=True)

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df.sample(5)

,title,authors,categories,description,average_rating,ratings_count,thumbnail,isbn13
4865,Baby Einstein: What Does Violet See? Raindrops...,Julie Aigner-Clark,Juvenile Fiction,A very special puddle sets Violet the mouse of...,3.25,16.0,http://books.google.com/books/content?id=95IIA...,9780786808717
6715,Lessons from Turtle Island,Guy W. Jones;Sally Moomaw,Education,The first comprehensive guide to addressing Na...,4.12,7.0,http://books.google.com/books/content?id=m5HoC...,9781929610259
4808,Soups,Norman Kolpas,Cooking,Offers a variety of recipes for both hot and c...,3.93,15.0,http://books.google.com/books/content?id=65dG-...,9780783502502
192,"Men Are from Mars, Women Are from Venus",John Gray,Family & Relationships,Rediscover the most famous relationship book e...,3.54,126108.0,http://books.google.com/books/content?id=MUw_d...,9780060574215
6623,The Art of Seduction,Robert Greene,Seduction,Which sort of seducer could you be: *Siren? *R...,4.06,13029.0,http://books.google.com/books/content?id=ZePgw...,9781861977694

In [50]:
df.shape

(6810, 8)

In [51]:
df.columns

Index(['title', 'authors', 'categories', 'description', 'average_rating',
       'ratings_count', 'thumbnail', 'isbn13'],
      dtype='object')

In [52]:
#creating a new column for tags
df['tags'] = df['title'] + ' ' + df['authors'] + ' ' + df['categories'] + ' ' + df['description']

In [53]:
df.sample(5)

,title,authors,categories,description,average_rating,ratings_count,thumbnail,isbn13,tags
4464,Star Trek: The Original Series: Crucible: Spoc...,David R. George III,Fiction,After watching his friend preserve the timelin...,3.95,201.0,http://books.google.com/books/content?id=jfO0x...,9780743491693,Star Trek: The Original Series: Crucible: Spoc...
5406,For the Sake of Argument,Christopher Hitchens,Literary Collections,"Essays discuss international politics, modern ...",4.17,217.0,http://books.google.com/books/content?id=pFmwv...,9780860916284,For the Sake of Argument Christopher Hitchens ...
4857,The Boys of Everest,Clint Willis,Sports & Recreation,Traces the mountaineering achievements of Chri...,3.86,431.0,http://books.google.com/books/content?id=8IBRP...,9780786715794,The Boys of Everest Clint Willis Sports & Recr...
327,The Dance of Intimacy,Harriet Lerner,Psychology,"In The Dance of Intimacy, the bestselling auth...",4.06,7128.0,http://books.google.com/books/content?id=tTKc8...,9780060916466,The Dance of Intimacy Harriet Lerner Psycholog...
6768,Design Like You Give a Damn,Architecture for Humanity (Organization),Architecture,Citing a harrowing lack of adequate shelter an...,4.11,770.0,http://books.google.com/books/content?id=jIJuQ...,9781933045252,Design Like You Give a Damn Architecture for H...

#data preprocessing

In [54]:
df['tags'][3]

"Rage of angels Sidney Sheldon Fiction A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power."

In [55]:
#libraries
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [56]:
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [57]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [58]:
#preprocessing
def preprocess(text):

  #lowercasing
  text = text.lower()

  #remove punctuation
  text = re.sub(r'[^a-zA-Z\s]','',text)

  #tokenization
  tokens = word_tokenize(text)

  #removing stopwords
  y = []
  for i in tokens:
    if i not in stop_words:
      y.append(i)

  #lammatizing
  x = []
  for i in y:
    x.append(lemmatizer.lemmatize(i))

  return " ".join(x)

In [59]:
df['tags'] = df['tags'].apply(preprocess)

In [60]:
df['tags'][2]

'one tree stephen r donaldson american fiction volume two stephen donaldsons acclaimed second trilogy featuing compelling antihero thomas covenant'

In [61]:
df.head()

,title,authors,categories,description,average_rating,ratings_count,thumbnail,isbn13,tags
0,Gilead,Marilynne Robinson,Fiction,A NOVEL THAT READERS and critics have been eag...,3.85,361.0,http://books.google.com/books/content?id=KQZCP...,9780002005883,gilead marilynne robinson fiction novel reader...
1,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,A new 'Christie for Christmas' -- a full-lengt...,3.83,5164.0,http://books.google.com/books/content?id=gA5GP...,9780002261982,spider web charles osborneagatha christie dete...
2,The One Tree,Stephen R. Donaldson,American fiction,Volume Two of Stephen Donaldson's acclaimed se...,3.97,172.0,http://books.google.com/books/content?id=OmQaw...,9780006163831,one tree stephen r donaldson american fiction ...
3,Rage of angels,Sidney Sheldon,Fiction,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,29532.0,http://books.google.com/books/content?id=FKo2T...,9780006178736,rage angel sidney sheldon fiction memorable me...
4,The Four Loves,Clive Staples Lewis,Christian life,Lewis' work on the nature of love divides love...,4.15,33684.0,http://books.google.com/books/content?id=XhQ5X...,9780006280897,four love clive staple lewis christian life le...

In [62]:
#extracting indices with index
indices = pd.Series(df.index,index=df['isbn13'])
indices.head()

isbn13
9780002005883    0
9780002261982    1
9780006163831    2
9780006178736    3
9780006280897    4
dtype: int64

In [63]:
indices.shape

(6810,)

#vectorization

In [64]:
#tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=10000,ngram_range=(1,2))

In [65]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [66]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 239720 stored elements and shape (6810, 10000)>

In [67]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
df.shape

(6810, 9)

#Recommendation using cosine similarity

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
#recomendation function
def recommend(title,n=10):
  if title not in indices:
    return ['Book not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df.iloc[similar_idx]

In [71]:
recommend("Spider's Web")

['Book not found']

#saving model

In [72]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb')) #tfidf matrix

pickle.dump(indices,open('indices.pkl','wb')) #indices

df.to_pickle('df.pkl') #books

pickle.dump(tfidf,open('tfidf.pkl','wb')) #tfidf